sudo: false

dist: trusty

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

before_script:
- python --version

# Note that default timeout is 10 minutes
# This can be changed with travis_wait, but that leads to
# issues with debug output:
# https://github.com/travis-ci/travis-ci/issues/5716
script:
  - python -m flake8
  - python run-tests.py --unit
  - if [[ $TRAVIS_EVENT_TYPE == 'cron' ]]; then travis_wait 60 python run-tests.py --books; fi;

notifications:
  email:
    recipients:
    - martinjrobins@gmail.com
    - michael.clerx@cs.ox.ac.uk
