sudo: false

dist: trusty

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  matrix:
    - PINTS_RUN_TESTS=true

matrix:
    include:
        # Coverage
        - python: "3.6"
          env: 
            - PINTS_COVERAGE=true  
            - PINTS_RUN_TESTS=false


# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install coverage
  - pip install codecov

before_script:
- python --version

# Note that default timeout is 10 minutes
# This can be changed with travis_wait, but that leads to
# issues with debug output:
# https://github.com/travis-ci/travis-ci/issues/5716
script:
  - python -m flake8
  - if [[ $PINTS_RUN_TESTS == true ]]; then python run-tests.py --unit; fi;
  - if [[ $TRAVIS_EVENT_TYPE == 'cron' ]]; then travis_wait 120 python run-tests.py --books; fi;
  - if [[ $PINTS_COVERAGE == true ]]; then coverage run run-tests.py --coverage; fi;

after_success:
  - if [[ $PINTS_COVERAGE ]]; then codecov; fi;

notifications:
  email:
    recipients:
    - martinjrobins@gmail.com
    - michael.clerx@cs.ox.ac.uk
