sudo: false

dist: trusty

language: python

matrix:
    include:
        # Unit testing on all supported Python versions on Ubuntu
        - python: "2.7"
          env:
            - PINTS_UNIT=true
          if: type != cron
        - python: "3.4"
          env:
            - PINTS_UNIT=true
          if: type != cron
        - python: "3.5"
          env:
            - PINTS_UNIT=true
          if: type != cron
        - python: "3.6"
          env:
            - PINTS_UNIT=true
          if: type != cron
        #- python: "3.7"
        #  env:
        #    - PINT_UNIT=true
        #  if: type != cron
        # Unit testing on OS/X
        - os: osx
          language: generic
          env:
            - PINTS_UNIT=true
        # Docs, style and cover checking, latest Python version only
        - python: "3.6"
          env:
            - PINTS_DOCS=true
          if: type != cron
        - python: "3.6"
          env:
            - PINTS_STYLE=true
          if: type != cron
        - python: "3.6"
          env:
            - PINTS_COVER=true
          if: type != cron
          # Cron jobs
        - python: "3.6"
          if: type == cron

# command to install dependencies
install:
  - pip install .
  - pip install -r requirements-dev.txt
  - if [[ $PINTS_COVER == true ]]; then pip install coverage codecov; fi;

before_script:
- python --version

# Note that default timeout is 10 minutes
# This can be changed with travis_wait, but that leads to
# issues with debug output:
# https://github.com/travis-ci/travis-ci/issues/5716
script:
  - if [[ $PINTS_UNIT == true ]]; then python run-tests.py --unit; fi;
  - if [[ $PINTS_DOCS == true ]]; then python run-tests.py --doctest; fi;
  - if [[ $PINTS_STYLE == true ]]; then python -m flake8; fi;
  - if [[ $PINTS_COVER == true ]]; then coverage run run-tests.py --nosub; fi;
  - if [[ $TRAVIS_EVENT_TYPE == 'cron' ]]; then travis_wait 120 python run-tests.py --books; fi;

after_success:
  - if [[ $PINTS_COVER == true ]]; then codecov; fi;

notifications:
  email:
    recipients:
    - martinjrobins@gmail.com
    - michael.clerx@cs.ox.ac.uk
