sudo: false

dist: trusty

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

before_script:
- python --version

script:
  - python -m flake8
  - python run-tests.py --unit --books

notifications:
  email:
    recipients:
    - martinjrobins@gmail.com
    - michael.clerx@cs.ox.ac.uk
